### ISSUE TITLE
Email to have the filters for which notifications are sent.

### ISSUE THREAD

**Issue by katta** [katta/jabfinder#13]
Current: `Vaccines are available in the following centers :`
Expected: `Vaccines are available in the following centers for 45+ from 19-06-2021`

**Comment by katta** [comment]
The current date is computed before it goes in to the watch loop on -notify flag. So if the jabfinder is started on day `x`, even on day `y` it uses the same date `x` because its already initialised in the filters which is never refreshed once it goes to the watch loop.

**Comment by kattarapido** [comment]
This commit 03b4527af fixes the date issue
