### ISSUE TITLE
Enable future date queries

### ISSUE THREAD

**Issue by CuriousCoder17** [katta/jabfinder#4]
@katta Shall we make the query date parameterised instead of using the system time? What do you think?

**Comment by katta** [comment]
We could by default it checks for a week from current day . But can add
start date as a param

**Comment by CuriousCoder17** [comment]
@katta Cool. I will raise a PR soon.

**Comment by CuriousCoder17** [comment]
![image](https://user-images.githubusercontent.com/16544355/120271525-1e72ff00-c2c9-11eb-93a0-6cfc3b4772bd.png)
![image](https://user-images.githubusercontent.com/16544355/120271544-2894fd80-c2c9-11eb-9deb-9d694ff90426.png)


@katta Can you please point me towards the section where we check one week from the date ? It seems to be just the current date for me..

**Comment by katta** [comment]
Yep the api by default fetches slots from the day given + 7 days .

**Comment by katta** [comment]
https://apisetu.gov.in/public/api/cowin#/Appointment%20Availability%20APIs/calendarByDistrict

**Comment by CuriousCoder17** [comment]
Raised a PR for this - https://github.com/katta/jabfinder/pull/5.

@katta Let me know if you need any changes.

**Comment by katta** [comment]
All good.. thanks for contributing @that-data-scientist :)

This PR https://github.com/katta/jabfinder/pull/5 closes this,
